name: DiscordBridge
main: live.amsleepy.discordbridge.DiscordBridge
version: 1.0.0
api-version: 1.13
author: sleepy

commands:
  discordbridge:
    description: "Main command for DiscordBridge plugin"
    aliases: [db]
    usage: "/<command> reload"
    permission: "discordbridge.admin"
  db:
    description: "Alias for discordbridge command"
    usage: "/<command> reload"
    permission: "discordbridge.admin"
permissions:
  discordbridge.admin:
    description: "Allows access to DiscordBridge administrative commands"
    default: op